///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package br.edu.utfpr.views;
//
//import br.edu.utfpr.dao.ClienteDao;
//import br.edu.utfpr.entidades.Cliente;
//import br.edu.utfpr.models.ClienteListModel;
//import java.util.List;
//
//public class FrmPesquisaCliente extends javax.swing.JInternalFrame {
//
//    private ClienteListModel clienteListModel;
//    private List<Cliente> listaCliente;
//
//    public FrmPesquisaCliente() {
//        initComponents();
//        super.setTitle("Tela de Clientes");
//        ClienteDao clienteDao = new ClienteDao();
//        listaCliente = clienteDao.findAll();
//        clienteListModel = new ClienteListModel(listaCliente);
//        tblClientes.setModel(clienteListModel);
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        txtNome = new javax.swing.JTextField();
//        btnPesquisar = new javax.swing.JButton();
//        jScrollPane2 = new javax.swing.JScrollPane();
//        tblClientes = new javax.swing.JTable();
//        jPanel2 = new javax.swing.JPanel();
//        btnIncluir = new javax.swing.JButton();
//        btnAlterar = new javax.swing.JButton();
//        btnExcluir = new javax.swing.JButton();
//
//        setClosable(true);
//        setIconifiable(true);
//        setMaximizable(true);
//        setResizable(true);
//        setTitle("..:: Pesquisa de Clientes ::..");
//        setToolTipText("");
//
//        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
//
//        jLabel1.setText("Nome :");
//
//        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
//            public void keyPressed(java.awt.event.KeyEvent evt) {
//                txtNomeKeyPressed(evt);
//            }
//            public void keyTyped(java.awt.event.KeyEvent evt) {
//                txtNomeKeyTyped(evt);
//            }
//        });
//
//        btnPesquisar.setText("Pesquisar");
//        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnPesquisarActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel1)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addComponent(btnPesquisar)
//                .addContainerGap())
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel1)
//                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(btnPesquisar))
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
//
//        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//
//            },
//            new String [] {
//                "Código", "Nome", "CPF", "Data Nascimento", "Sexo"
//            }
//        ) {
//            Class[] types = new Class [] {
//                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
//            };
//            boolean[] canEdit = new boolean [] {
//                false, false, false, false, false
//            };
//
//            public Class getColumnClass(int columnIndex) {
//                return types [columnIndex];
//            }
//
//            public boolean isCellEditable(int rowIndex, int columnIndex) {
//                return canEdit [columnIndex];
//            }
//        });
//        jScrollPane2.setViewportView(tblClientes);
//
//        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);
//
//        btnIncluir.setText("Novo");
//        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnIncluirActionPerformed(evt);
//            }
//        });
//        jPanel2.add(btnIncluir);
//
//        btnAlterar.setText("Editar");
//        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnAlterarActionPerformed(evt);
//            }
//        });
//        jPanel2.add(btnAlterar);
//
//        btnExcluir.setText("Excluir");
//        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnExcluirActionPerformed(evt);
//            }
//        });
//        jPanel2.add(btnExcluir);
//
//        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
//        FrmCliente frmCliente = new FrmCliente(null, true);
//        frmCliente.setLocationRelativeTo(null);
//        frmCliente.setVisible(true);
//    }//GEN-LAST:event_btnIncluirActionPerformed
//
//    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
//    }//GEN-LAST:event_btnAlterarActionPerformed
//
//    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
//    }//GEN-LAST:event_btnExcluirActionPerformed
//
//    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
//
//
//    }//GEN-LAST:event_btnPesquisarActionPerformed
//
//    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtNomeKeyTyped
//
//    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
//        btnPesquisarActionPerformed(null);
//    }//GEN-LAST:event_txtNomeKeyPressed
//
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton btnAlterar;
//    private javax.swing.JButton btnExcluir;
//    private javax.swing.JButton btnIncluir;
//    private javax.swing.JButton btnPesquisar;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    private javax.swing.JScrollPane jScrollPane2;
//    private javax.swing.JTable tblClientes;
//    private javax.swing.JTextField txtNome;
//    // End of variables declaration//GEN-END:variables
//
//}
